### ISSUE TITLE
Trying to Connect Collabora/code to this container

### ISSUE THREAD

**Issue by Ryu945** [pini-gh/docker-letsencrypt-nginx-proxy-companion#5]
When I publish a port besides 80 and 443 in this container, it doesn't make any attempt to proxy that new port.  I checked the file created and it only made rules for port 80 and 443  In my case, I tried to publish port 9980 for a Collabora/Code container.   The certificate creation appears to work correctly but the reverse proxy only sets itself up on port 80/443.

**Comment by pini-gh** [comment]
As you describe it, this issue seems related to pini-gh/nginx-proxy, and not to pini-gh/docker-letsencrypt-nginx-proxy-companion. Is that correct?
And please post your redacted docker-compose.yml file so I could understand what you're trying to do.

**Comment by Ryu945** [comment]
I realized I posted this on the wrong repository and put my response here.

https://github.com/pini-gh/nginx-proxy/issues/1

**Comment by pini-gh** [comment]
> I realized I posted this on the wrong repository and put my response here.
> 
> [pini-gh/nginx-proxy#1](https://github.com/pini-gh/nginx-proxy/issues/1)

Closing this one then.
